name: Remote SSH Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Server via SSH
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                fingerprint: ""
                debug: true
                script: |
                    pwd
                    cd bingo.dougdragon.com
                    cd cokenortheast
                    cd cne-bingo
                    git pull origin main
                    echo "Deployment successful."
